name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "*"
        target: "~/htmlcss-temp"

    - name: Deploy on EC2 (move files to nginx folder)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo rm -rf /var/www/portfolio/*
          sudo mv ~/htmlcss-temp/* /var/www/portfolio/
          sudo chown -R www-data:www-data /var/www/portfolio
          sudo systemctl reload nginx
